version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PGUSER:-admin}  # Fallback to 'admin' if not set
      POSTGRES_PASSWORD: ${PGPASSWORD:-secret}
      POSTGRES_DB: ${PGDATABASE:-afro_rus_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      RAILWAY_PRIVATE_DOMAIN: postgres  # Maps to the service name in Docker
      PGPORT: 5432
      PGDATABASE: ${PGDATABASE:-afro_rus_db}
      PGUSER: ${PGUSER:-admin}
      PGPASSWORD: ${PGPASSWORD:-secret}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      PORT: 8080
      DATABASE_URL: postgresql://$${RAILWAY_PRIVATE_DOMAIN}:$${PGPORT:5432}/$${PGDATABASE}?sslmode=disable
volumes:
  postgres_data: