version: '3.8'  # You can remove this line if using newer Docker Compose versions

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  springboot-app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: afro-rus-backend
    container_name: afro-rus-springboot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_HOST: ${SPRING_DATASOURCE_HOST}
      SPRING_DATASOURCE_PORT: ${SPRING_DATASOURCE_PORT}
      SPRING_DATASOURCE_DATABASE: ${SPRING_DATASOURCE_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
      # Add more Spring properties as needed

volumes:
  postgres_data: