version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: afro-rus-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/afrorus_db
      - SPRING_DATASOURCE_USERNAME=afro_user
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: afro_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: afrorus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
