spring:
  datasource:
    url: jdbc:postgresql://${RAILWAY_PRIVATE_DOMAIN:localhost}:${PGPORT:5432}/${PGDATABASE:afro_rus_db}?sslmode=disable
    username: ${PGUSER:admin}
    password: ${PGPASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use 'validate', 'update', 'create', or 'create-drop' based on your use case
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

# Optional: for logging or debugging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
